# Generated by Django 5.1.7 on 2025-03-17 11:55

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_rename_reply_comment_parent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentinteraction',
            old_name='news',
            new_name='comment',
        ),
        migrations.AlterUniqueTogether(
            name='commentinteraction',
            unique_together={('comment', 'user')},
        ),
    ]
