# Generated by Django 5.1.7 on 2025-03-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_news_commentinteraction_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsmedia',
            name='is_head_page',
            field=models.BooleanField(default=False),
        ),
    ]
