# Generated by Django 5.1.7 on 2025-03-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='phone_number',
            field=models.CharField(db_index=True, default=9190257536, max_length=11, unique=True),
            preserve_default=False,
        ),
    ]
